version: "3.8"
services:
  myapp:
    build: .
    volumes:
      - .:/app
    working_dir: /app
#    stdin_open: true   # keep STDIN open
#    tty: true          # allocate a pseudo-TTY
#    command: tail -f /dev/null
    command: sleep infinity
    stop_grace_period: 1s   # default is 10s
